# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'designerEumRLd.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2 import QtGui
from PySide2 import QtWidgets
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(800, 600))
        self.ConnectBtn = QPushButton(self.centralwidget)
        self.ConnectBtn.setObjectName(u"ConnectBtn")
        self.ConnectBtn.setGeometry(QRect(340, 236, 75, 23))

        self.server_RBGrp = QButtonGroup(self.centralwidget)
        self.WindowsRB = QRadioButton(self.centralwidget)
        self.WindowsRB.setObjectName(u"WindowsRB")
        self.WindowsRB.setGeometry(QRect(340, 186, 82, 17))
        self.server_RBGrp.addButton(self.WindowsRB)
        self.LinuxRB = QRadioButton(self.centralwidget)
        self.LinuxRB.setObjectName(u"LinuxRB")
        self.LinuxRB.setGeometry(QRect(340, 206, 82, 17))
        self.server_RBGrp.addButton(self.LinuxRB)

        self.ServerInp = QLineEdit(self.centralwidget)
        self.ServerInp.setObjectName(u"ServerInp")
        self.ServerInp.setGeometry(QRect(330, 126, 113, 20))
        self.PwdInp = QLineEdit(self.centralwidget)
        self.PwdInp.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PwdInp.setObjectName(u"PwdInp")
        self.PwdInp.setGeometry(QRect(330, 156, 113, 20))
        
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(241, 129, 81, 20))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(270, 160, 47, 13))
        self.ConnStatusTxt = QLabel(self.centralwidget)
        self.ConnStatusTxt.setObjectName(u"ConnStatusTxt")
        self.ConnStatusTxt.setGeometry(QRect(300, 270, 161, 41))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ConnStatusTxt.setFont(font)
        self.ConnStatusTxt.setLayoutDirection(Qt.LeftToRight)
        self.ConnStatusTxt.setStyleSheet(u"color : red")
        self.ConnStatusTxt.setTextFormat(Qt.AutoText)
        self.ConnStatusTxt.setAlignment(Qt.AlignCenter)

        self.CPUper_RBGrp = QButtonGroup(self.centralwidget)
        self.CPUper25RB = QRadioButton(self.centralwidget)
        self.CPUper25RB.setObjectName(u"CPUper25RB")
        self.CPUper25RB.setGeometry(QRect(360, 380, 82, 17))
        self.CPUper_RBGrp.addButton(self.CPUper25RB)
        self.CPUper50RB = QRadioButton(self.centralwidget)
        self.CPUper50RB.setObjectName(u"CPUper50RB")
        self.CPUper50RB.setGeometry(QRect(360, 400, 82, 17))
        self.CPUper_RBGrp.addButton(self.CPUper50RB)
        self.CPUper100RB = QRadioButton(self.centralwidget)
        self.CPUper100RB.setObjectName(u"CPUper100RB")
        self.CPUper100RB.setGeometry(QRect(360, 440, 82, 17))
        self.CPUper_RBGrp.addButton(self.CPUper100RB)
        self.CPUper75RB = QRadioButton(self.centralwidget)
        self.CPUper75RB.setObjectName(u"CPUper75RB")
        self.CPUper75RB.setGeometry(QRect(360, 420, 82, 17))
        self.CPUper_RBGrp.addButton(self.CPUper75RB)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(330, 330, 111, 31))
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setUnderline(True)
        font1.setWeight(75)
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.DurationInp = QSpinBox(self.centralwidget)
        self.DurationInp.setObjectName(u"DurationInp")
        self.DurationInp.setGeometry(QRect(360, 490, 42, 22))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 494, 47, 13))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(417, 494, 47, 13))
        self.ExecuteBtn = QPushButton(self.centralwidget)
        self.ExecuteBtn.setObjectName(u"ExecuteBtn")
        self.ExecuteBtn.setGeometry(QRect(350, 540, 75, 23))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(240, 40, 281, 31))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setUnderline(True)
        font2.setWeight(75)
        self.label_6.setFont(font2)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.UserInp = QLineEdit(self.centralwidget)
        self.UserInp.setObjectName(u"UserInp")
        self.UserInp.setGeometry(QRect(330, 97, 113, 20))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(261, 100, 61, 20))
        self.ExecStatusTxt = QLabel(self.centralwidget)
        self.ExecStatusTxt.setObjectName(u"ExecStatusTxt")
        self.ExecStatusTxt.setGeometry(QRect(310, 570, 151, 20))
        self.ExecStatusTxt.setFont(font)
        self.ExecStatusTxt.setStyleSheet(u"color : green")
        self.ExecStatusTxt.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.ConnectBtn.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.WindowsRB.setText(QCoreApplication.translate("MainWindow", u"Windows", None))
        self.LinuxRB.setText(QCoreApplication.translate("MainWindow", u"Linux", None))
#if QT_CONFIG(whatsthis)
        self.ServerInp.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.ServerInp.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Server Address", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Password", None))
        self.ConnStatusTxt.setText(QCoreApplication.translate("MainWindow", u"Not Connected", None))
        self.CPUper25RB.setText(QCoreApplication.translate("MainWindow", u"25%", None))
        self.CPUper50RB.setText(QCoreApplication.translate("MainWindow", u"50%", None))
        self.CPUper100RB.setText(QCoreApplication.translate("MainWindow", u"100%", None))
        self.CPUper75RB.setText(QCoreApplication.translate("MainWindow", u"75%", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"CPU Stress", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Duration", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Seconds", None))
        self.ExecuteBtn.setText(QCoreApplication.translate("MainWindow", u"Execute", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"SRE Toolkit v0.1", None))
#if QT_CONFIG(whatsthis)
        self.UserInp.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        self.UserInp.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"User Name", None))
        self.ExecStatusTxt.setText("")
    # retranslateUi

